name: beats_ui
description: Development frontend for the beats project.
# version: 0.0.1
# homepage: https://github.com/hugovdm/beats

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  bson: ^1.0.3

dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
  pedantic: ^1.11.1
